const dummyProducts = [
  // Fashion Apparel (10)
  {
    id: 1,
    title: "Men's Casual T-Shirt",
    slug: "fashion-apparel",
    price: 799,
    image: "https://images.unsplash.com/photo-1618453292459-53424b66bb6a?q=80&w=3164&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    fallbackImage: "https://source.unsplash.com/400x400/?clothes",
    specifications: [
      "100% Cotton",
      "Slim fit design",
      "Available in 3 colors",
      "Machine washable",
    ],
  },
  {
    id: 2,
    title: "Women's Denim Jacket",
    slug: "fashion-apparel",
    price: 2199,
    image: "https://source.unsplash.com/400x400/?denim,jacket,women,fashion",
    fallbackImage: "https://source.unsplash.com/400x400/?jacket",
    specifications: [
      "Denim fabric",
      "Button closure",
      "Two front pockets",
      "Regular fit",
    ],
  },
  {
    id: 3,
    title: "Men's Running Shoes",
    slug: "fashion-apparel",
    price: 3199,
    image: "https://source.unsplash.com/400x400/?shoes,men,running",
    fallbackImage: "https://source.unsplash.com/400x400/?shoes",
    specifications: [
      "Breathable mesh",
      "Rubber sole",
      "Lightweight",
      "Available in 5 colors",
    ],
  },
  {
    id: 4,
    title: "Women's Handbag",
    slug: "fashion-apparel",
    price: 2799,
    image: "https://source.unsplash.com/400x400/?handbag,women,fashion",
    fallbackImage: "https://source.unsplash.com/400x400/?bag",
    specifications: [
      "Leather material",
      "Adjustable strap",
      "Multiple compartments",
    ],
  },
  {
    id: 5,
    title: "Unisex Sunglasses",
    slug: "fashion-apparel",
    price: 999,
    image: "https://source.unsplash.com/400x400/?sunglasses,unisex,fashion",
    fallbackImage: "https://source.unsplash.com/400x400/?sunglasses",
    specifications: [
      "UV protection",
      "Scratch-resistant lenses",
      "Lightweight frame",
    ],
  },
  {
    id: 6,
    title: "Sports Cap",
    slug: "fashion-apparel",
    price: 499,
    image: "/images/fashion6.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Adjustable strap",
      "Breathable fabric",
      "One size fits all",
    ],
  },
  {
    id: 7,
    title: "Cotton Socks (5 Pack)",
    slug: "fashion-apparel",
    price: 699,
    image: "/images/fashion7.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Soft cotton blend",
      "Breathable",
      "Elastic cuffs",
      "Multi-color pack",
    ],
  },
  {
    id: 8,
    title: "Elegant Wristwatch",
    slug: "fashion-apparel",
    price: 4999,
    image: "/images/fashion8.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Quartz movement",
      "Water resistant",
      "Leather strap",
      "Minimalist design",
    ],
  },
  {
    id: 9,
    title: "Women’s Scarf",
    slug: "fashion-apparel",
    price: 699,
    image: "/images/fashion9.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Lightweight fabric",
      "Soft texture",
      "Multiple colors",
    ],
  },
  {
    id: 10,
    title: "Backpack",
    slug: "fashion-apparel",
    price: 1599,
    image: "/images/fashion10.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Water resistant",
      "Multiple compartments",
      "Ergonomic straps",
    ],
  },

  // Electronics (10)
  {
    id: 11,
    title: "Smartphone X200",
    slug: "electronics",
    price: 25999,
    image: "https://source.unsplash.com/400x400/?smartphone,mobile,electronics",
    fallbackImage: "https://source.unsplash.com/400x400/?phone",
    specifications: [
      "6.7 inch AMOLED display",
      "128GB storage",
      "Quad camera setup",
      "4500mAh battery",
      "5G enabled",
    ],
  },
  {
    id: 12,
    title: "Wireless Earbuds",
    slug: "electronics",
    price: 5999,
    image: "https://source.unsplash.com/400x400/?earbuds,wireless,audio",
    fallbackImage: "https://source.unsplash.com/400x400/?earbuds",
    specifications: [
      "Noise cancellation",
      "Bluetooth 5.0",
      "24 hours battery life",
    ],
  },
  {
    id: 13,
    title: "Gaming Laptop",
    slug: "electronics",
    price: 85999,
    image: "https://source.unsplash.com/400x400/?gaming,laptop,electronics",
    fallbackImage: "https://source.unsplash.com/400x400/?laptop",
    specifications: [
      "Intel i7 processor",
      "16GB RAM",
      "NVIDIA RTX 3060",
      "512GB SSD",
    ],
  },
  {
    id: 14,
    title: "Smartwatch Pro",
    slug: "electronics",
    price: 12999,
    image: "https://source.unsplash.com/400x400/?smartwatch,electronics,wearable",
    fallbackImage: "https://source.unsplash.com/400x400/?watch",
    specifications: [
      "Heart rate monitor",
      "GPS tracking",
      "Water resistant",
    ],
  },
  {
    id: 15,
    title: "4K LED TV",
    slug: "electronics",
    price: 45999,
    image: "https://source.unsplash.com/400x400/?4k,tv,electronics",
    fallbackImage: "https://source.unsplash.com/400x400/?television",
    specifications: [
      "55 inch display",
      "HDR10+ support",
      "Smart TV features",
    ],
  },
  {
    id: 16,
    title: "Laptop Cooling Pad",
    slug: "electronics",
    price: 899,
    image: "/images/electronics6.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "USB powered",
      "3 fan speed levels",
      "Ergonomic design",
    ],
  },
  {
    id: 17,
    title: "HD Webcam",
    slug: "electronics",
    price: 1799,
    image: "/images/electronics7.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "1080p video",
      "Built-in microphone",
      "Plug & play USB",
    ],
  },
  {
    id: 18,
    title: "Portable Charger 10000mAh",
    slug: "electronics",
    price: 1499,
    image: "/images/electronics8.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Dual USB ports",
      "Fast charging",
      "Compact design",
    ],
  },
  {
    id: 19,
    title: "Gaming Mouse",
    slug: "electronics",
    price: 2499,
    image: "/images/electronics9.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "RGB lighting",
      "Ergonomic design",
      "Adjustable DPI",
    ],
  },
  {
    id: 20,
    title: "Mechanical Keyboard",
    slug: "electronics",
    price: 3999,
    image: "/images/electronics10.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "RGB backlit keys",
      "Mechanical switches",
      "USB wired",
    ],
  },

  // Computers (10)
  {
    id: 21,
    title: "Mechanical Keyboard",
    slug: "computers",
    price: 4999,
    image: "https://source.unsplash.com/400x400/?keyboard,mechanical,computer",
    fallbackImage: "https://source.unsplash.com/400x400/?keyboard",
    specifications: [
      "RGB backlight",
      "Cherry MX switches",
      "Ergonomic design",
    ],
  },
  {
    id: 22,
    title: "Wireless Mouse",
    slug: "computers",
    price: 1499,
    image: "https://source.unsplash.com/400x400/?mouse,wireless,computer",
    fallbackImage: "https://source.unsplash.com/400x400/?mouse",
    specifications: [
      "2.4GHz wireless",
      "Adjustable DPI",
      "Rechargeable battery",
    ],
  },
  {
    id: 23,
    title: "27 inch Monitor",
    slug: "computers",
    price: 17999,
    image: "https://source.unsplash.com/400x400/?monitor,computer",
    fallbackImage: "https://source.unsplash.com/400x400/?screen",
    specifications: [
      "2560x1440 resolution",
      "IPS panel",
      "75Hz refresh rate",
    ],
  },
  {
    id: 24,
    title: "External Hard Drive",
    slug: "computers",
    price: 5999,
    image: "https://source.unsplash.com/400x400/?hard-drive,external,computer",
    fallbackImage: "https://source.unsplash.com/400x400/?hard-drive",
    specifications: [
      "2TB storage",
      "USB 3.0",
      "Portable design",
    ],
  },
  {
    id: 25,
    title: "USB-C Hub",
    slug: "computers",
    price: 2999,
    image: "https://source.unsplash.com/400x400/?usb-hub,computer",
    fallbackImage: "https://source.unsplash.com/400x400/?usb",
    specifications: [
      "4 ports",
      "Aluminum body",
      "Plug and play",
    ],
  },
  {
    id: 26,
    title: "Gaming Headset",
    slug: "computers",
    price: 2999,
    image: "/images/computers6.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Surround sound",
      "Noise cancelling mic",
      "LED lights",
    ],
  },
  {
    id: 27,
    title: "Laptop Stand",
    slug: "computers",
    price: 899,
    image: "/images/computers7.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Aluminum build",
      "Adjustable height",
      "Portable design",
    ],
  },
  {
    id: 28,
    title: "Webcam Cover",
    slug: "computers",
    price: 199,
    image: "/images/computers8.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Slide cover",
      "Adhesive backing",
    ],
  },
  {
    id: 29,
    title: "Mechanical Keyboard Pro",
    slug: "computers",
    price: 4999,
    image: "/images/computers9.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "RGB lighting",
      "Mechanical switches",
      "Wired USB",
    ],
  },
  {
    id: 30,
    title: "Graphic Tablet",
    slug: "computers",
    price: 7999,
    image: "/images/computers10.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Pressure sensitive",
      "Compact size",
      "Compatible with major OS",
    ],
  },

  // Home & Garden (10)
  {
    id: 31,
    title: "LED Desk Lamp",
    slug: "home-garden",
    price: 1299,
    image: "https://source.unsplash.com/400x400/?desk-lamp,light,home",
    fallbackImage: "https://source.unsplash.com/400x400/?lamp",
    specifications: [
      "Adjustable brightness",
      "Touch control",
      "USB charging port",
    ],
  },
  {
    id: 32,
    title: "Indoor Plant Set",
    slug: "home-garden",
    price: 1599,
    image: "https://source.unsplash.com/400x400/?indoor-plant,home,garden",
    fallbackImage: "https://source.unsplash.com/400x400/?plant",
    specifications: [
      "Set of 3 plants",
      "Low maintenance",
      "Air purifying",
    ],
  },
  {
    id: 33,
    title: "Garden Tools Kit",
    slug: "home-garden",
    price: 2199,
    image: "https://source.unsplash.com/400x400/?garden-tools,gardening",
    fallbackImage: "https://source.unsplash.com/400x400/?tools",
    specifications: [
      "5 pieces",
      "Stainless steel",
      "Ergonomic handles",
    ],
  },
  {
    id: 34,
    title: "Coffee Maker",
    slug: "home-garden",
    price: 3499,
    image: "https://source.unsplash.com/400x400/?coffee-maker,kitchen",
    fallbackImage: "https://source.unsplash.com/400x400/?coffee",
    specifications: [
      "Programmable timer",
      "12 cup capacity",
      "Auto shut-off",
    ],
  },
  {
    id: 35,
    title: "Wall Art Painting",
    slug: "home-garden",
    price: 2199,
    image: "https://source.unsplash.com/400x400/?wall-art,painting,home",
    fallbackImage: "https://source.unsplash.com/400x400/?art",
    specifications: [
      "Canvas print",
      "Modern design",
      "Ready to hang",
    ],
  },
  {
    id: 36,
    title: "Smart Thermostat",
    slug: "home-garden",
    price: 6999,
    image: "/images/home6.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "WiFi enabled",
      "Remote control",
      "Energy saving",
    ],
  },
  {
    id: 37,
    title: "Ceramic Vase",
    slug: "home-garden",
    price: 799,
    image: "/images/home7.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Handcrafted",
      "12 inch height",
      "Glossy finish",
    ],
  },
  {
    id: 38,
    title: "Cookware Set",
    slug: "home-garden",
    price: 4999,
    image: "/images/home8.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "10-piece set",
      "Non-stick coating",
      "Dishwasher safe",
    ],
  },
  {
    id: 39,
    title: "Robot Vacuum Cleaner",
    slug: "home-garden",
    price: 15999,
    image: "/images/home9.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Auto charging",
      "Multiple cleaning modes",
      "Compact design",
    ],
  },
  {
    id: 40,
    title: "Outdoor String Lights",
    slug: "home-garden",
    price: 1199,
    image: "/images/home10.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Weather resistant",
      "20 LED bulbs",
      "8 modes",
    ],
  },

  // Collectibles (10)
  {
    id: 41,
    title: "Vintage Comic Book",
    slug: "collectibles",
    price: 3499,
    image: "https://source.unsplash.com/400x400/?comic-book,vintage",
    fallbackImage: "https://source.unsplash.com/400x400/?comic",
    specifications: [
      "First edition",
      "Excellent condition",
      "Rare collectible",
    ],
  },
  {
    id: 42,
    title: "Antique Vase",
    slug: "collectibles",
    price: 7999,
    image: "https://source.unsplash.com/400x400/?antique,vase",
    fallbackImage: "https://source.unsplash.com/400x400/?vase",
    specifications: [
      "Porcelain",
      "Hand-painted",
      "19th century",
    ],
  },
  {
    id: 43,
    title: "Classic Vinyl Record",
    slug: "collectibles",
    price: 1599,
    image: "https://source.unsplash.com/400x400/?vinyl-record,music",
    fallbackImage: "https://source.unsplash.com/400x400/?vinyl",
    specifications: [
      "Limited edition",
      "High fidelity sound",
    ],
  },
  {
    id: 44,
    title: "Retro Camera",
    slug: "collectibles",
    price: 4999,
    image: "https://source.unsplash.com/400x400/?retro-camera,vintage",
    fallbackImage: "https://source.unsplash.com/400x400/?camera",
    specifications: [
      "35mm film",
      "Manual focus",
      "Collectible item",
    ],
  },
  {
    id: 45,
    title: "Signed Baseball",
    slug: "collectibles",
    price: 2999,
    image: "https://source.unsplash.com/400x400/?baseball,signed,collectible",
    fallbackImage: "https://source.unsplash.com/400x400/?baseball",
    specifications: [
      "Autographed",
      "Official league ball",
    ],
  },

  {
    id: 46,
    title: "Model Airplane",
    slug: "collectibles",
    price: 2199,
    image: "/images/collectibles6.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Hand-painted",
      "Wooden body",
      "Collector's display stand",
    ],
  },
  {
    id: 47,
    title: "Rare Stamp Collection",
    slug: "collectibles",
    price: 1299,
    image: "/images/collectibles7.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Vintage stamps",
      "Limited edition",
      "Protective album",
    ],
  },
  {
    id: 48,
    title: "Action Figure Set",
    slug: "collectibles",
    price: 3499,
    image: "/images/collectibles8.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Limited edition",
      "Includes 5 figures",
      "Collector packaging",
    ],
  },
  {
    id: 49,
    title: "Autographed Poster",
    slug: "collectibles",
    price: 1799,
    image: "/images/collectibles9.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "Signed by artist",
      "Glossy finish",
      "Limited print",
    ],
  },
  {
    id: 50,
    title: "Classic Movie DVD Set",
    slug: "collectibles",
    price: 999,
    image: "/images/collectibles10.jpg",
    fallbackImage: "/images/fallback.jpg",
    specifications: [
      "10 classic movies",
      "DVD format",
      "Collector's edition",
    ],
  },
];

export default dummyProducts;